---
- name: Install pip
  apt:
    name: python3-pip

- name: Install docker python
  pip:
    name: docker-py

- name: Run reddit container
  docker_container:
    name: Reddit
    image: tomorrowcanw8/otus-reddit:1.0
    ports: 80:9292
