version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  mongodb-exporter:
    image: ${USER_NAME}/mongodb-exporter:${MONGO_EXP_VER}
    networks:
      - back_net
    command:
      - '--mongodb.uri=mongodb://post_db:27017'

  ui:
#    build: ./ui
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
#    build: ./post-py
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      - front_net
      - back_net
  comment:
#    build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  blackbox-exporter:
    image: ${USER_NAME}/blackbox-exporter:${BBOX_EXP_VER}
    ports:
      - 9115:9115
    networks:
      - front_net
      - back_net


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
#    name: back_net
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
#    name: front_net
    ipam:
      config:
        - subnet: 10.0.1.0/24
