version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
#    name: back_net
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
#    name: front_net
    ipam:
      config:
        - subnet: 10.0.1.0/24
